---
- name: Gather IOS facts from Cisco devices
  hosts: routers
  gather_facts: no
  collections:
    - cisco.ios

  tasks:
    - name: Collect IOS facts
      ios_facts:
      register: ios_device_facts

    - name: Display hostname and version
      debug:
        msg: "Device {{ inventory_hostname }} is running {{ ios_device_facts.ansible_facts.ansible_net_version }}"
